### ISSUE TITLE
Use config file for services

### ISSUE THREAD

**Issue by pathmapper** [kreis-viersen/quattromap#7]
Use a config file to make it easier to use custom services. Also the code related to the services could be simplified/refactored.

**Comment by Frankboen** [comment]
Kreis Warendorf, Amt für Geoinformation: 
Nice and helpful tool! A config file for easy editing WMS-URL would be great.

**Comment by Frankboen** [comment]
Kreis Warendorf:
I would like to create perma-links to adjust to different local authority districts.

**Comment by pathmapper** [comment]
Thanks for your feedback @Frankboen, moved the permalink feature request to an own issue -> https://github.com/kreis-viersen/quattromap/issues/9
