### ISSUE TITLE
Permalink

### ISSUE THREAD

**Issue by pathmapper** [kreis-viersen/quattromap#9]
Kreis Warendorf:
I would like to create perma-links to adjust to different local authority districts.

_Originally posted by @Frankboen in https://github.com/kreis-viersen/quattromap/issues/7#issuecomment-765356079_

**Comment by pathmapper** [comment]
@Frankboen thanks for the suggestion! Additionally such a permalink could include the quattromap settings, all in all:

- center of the map(s)
- zoom level
- number of maps
- selected layers and overlays
- colour of the crosshair

**Comment by Frankboen** [comment]
Hallo,
Perma-Link und cofig.json: Super Job!
Besten Dank und Grüße aus dem Kreis Warendorf


Mit freundlichem Gruß
Im Auftrag

Frank Böning

Kreis Warendorf
Amt für Geoinformation und Kataster
-Geoinformation, Geodatenzentrum-
Postfach 110561, 48207 Warendorf
Dienstgebäude: Waldenburger Straße 2, 48231 Warendorf
Telefon: 02581 53 6236, Fax:(02581) 53-6299 E-Mail: frank.boening@kreis-warendorf.de<mailto:frank.boening@kreis-warendorf.de>, Raum C 3.42

Besuchen Sie das Geoportal des Kreises Warendorf: http://geoportal.kreis-warendorf.de<http://geoportal.kreis-warendorf.de/>


Von: pathmapper <notifications@github.com>
Gesendet: Freitag, 19. Februar 2021 11:19
An: kreis-viersen/quattromap <quattromap@noreply.github.com>
Cc: Böning, Frank <Frank.Boening@kreis-warendorf.de>; Mention <mention@noreply.github.com>
Betreff: Re: [kreis-viersen/quattromap] Permalink (#9)


Closed #9<https://github.com/kreis-viersen/quattromap/issues/9> via #17<https://github.com/kreis-viersen/quattromap/pull/17>.
